sequence:
  - ':f1 => <>:f2'
  - '~:f1 => ~<>:f2'
  - '[]~(:f1 & :f2)'

multiple_merge:
  - ':f1 => (<>:f2 & ~<>:f3) | (~<>:f2 & <>:f3)'
  - '~:f1 => ~((<>:f2 & ~<>:f3) | (~<>:f2 & <>:f3))'
  - ':f2 | :f3 => <>:f4'
  - '~(:f2 | :f3) => ~<>:f4'
  - '[]~(:f1 & :f4)'
  - '[]~(:f2 & :f3)'
  - '[]~(:f1 & (:f2 | :f3))'
  - '[]~((:f2 | :f3) & :f4)'