require 'bpmn/pattern/base'
require 'bpmn/pattern/exclusive_choice'
require 'bpmn/pattern/multi_choice'
require 'bpmn/pattern/multiple_merge'
require 'bpmn/pattern/parallel_split'
require 'bpmn/pattern/sequence'
require 'bpmn/pattern/simple_merge'
require 'bpmn/pattern/synchronization'